version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app

    environment:
      - EXPRESS_PORT=8000
    command: go run cmd/main.go -b 0.0.0.0
